openfun/mork

- .circleci/config.yml
- docker-compose.yml
- src/mork/conf.py
- Release workflow was triggered on tags and on changes on the `main` branch. Changing it so it is triggered only on tags.
- Pylint is not used in Mork, removing remaining parts of config and escapes from the project.
> 💚(circle) trigger release only on tags

- .github/ISSUE_TEMPLATE/Support_question.md
- src/mork/edx/database.py
- src/mork/edx/mixins.py
- src/mork/edx/models.py
- tests/conftest.py
- tests/edx/test_mixins.py
- tests/edx/test_models.py
- tests/fixtures/db.py
To be able to warn/delete inactive users by batch, add a method to get the inactive users count.
As we now have multiple queries for getting inactive users informations, we should not compute the threshold date inside the query helpers, but we should compute it before and pass the threshold date to query helpers.
On a side note, fixing typo inside GitHub template
> 🧐(project) add method to retrieve inactive user count from edx database

- .circleci/config.yml
The job for publicating Mork Python package to PyPi is failing. Fixing it.
> 🐛(circle) fix publication to pypi job

- .env.dist
- src/app/mork/conf.py
- src/app/pyproject.toml
An issue was encountered when deploying and connecting to our PostgreSQL databases with psycopg (version 3): https://github.com/psycopg/psycopg/issues/813
We could have changed the encoding in the URL, but I think we should stick to psycopg2 for now.
> ⬇️(project) downgrade psycopg driver to psycopg2

- .env.dist
- CHANGELOG.md
- src/app/mork/celery/deletion_tasks.py
- src/app/mork/conf.py
- src/app/mork/tests/celery/test_deletion_task.py
- src/app/mork/tests/celery/test_emailing_tasks.py
- src/app/mork/tests/edx/test_mixins.py
- src/app/pyproject.toml
Now that we'll have proper SQLAlchemy models of user data from the edx database,
create a task that gets the inactive users and trigger deletion subtasks.
> ✨(celery) implement main deletion task

- src/app/mork/api/models.py
- src/app/mork/api/routes/tasks.py
- src/app/mork/tests/api/test_tasks.py
Previously, the API could only trigger the Celery task to delete all inactive users. This update adds the ability to trigger the deletion of a specific user.
> ✨(api) add support for deleting a single user via api

- CHANGELOG.md
- bin/seed_edx_database.py
- src/app/mork/edx/factories/auth.py
- src/app/mork/edx/factories/base.py
- src/app/mork/edx/factories/bulk.py
- src/app/mork/edx/factories/certificates.py
- src/app/mork/edx/factories/contentstore.py
- src/app/mork/edx/factories/course.py
- src/app/mork/edx/factories/courseware.py
- src/app/mork/edx/factories/dark.py
- src/app/mork/edx/factories/django.py
- src/app/mork/edx/factories/instructor.py
- src/app/mork/edx/factories/notify.py
- src/app/mork/edx/factories/payment.py
- src/app/mork/edx/factories/proctoru.py
- src/app/mork/edx/factories/student.py
- src/app/mork/edx/factories/user.py
- src/app/mork/edx/factories/util.py
- src/app/mork/edx/factories/verify.py
- src/app/mork/edx/models/auth.py
- src/app/mork/edx/models/student.py
- src/app/mork/tests/fixtures/db.py
1. The relationships in the `student_manualenrollmentaudit` are incorrect.
2. Since the introduction of the edx MySQL models, the seeding script has stopped working.
1. [x] The `student_manualenrollmentaudit` table is a child of the `student_coursenrollment` table, which is a child of the `auth_user` table. When a user is deleted, Mork should delete the corresponding enrollments and the corresponding manual enrollment audits. We don't want to delete based on the `enrolled_by` field
2. [x] We rely on factories to generate fake data into the MySQL development database. To ensure compatibility with both testing and seeding use cases, the factories need some proper configuration, mainly on handling the session and the persistency.
Additionally, subfactories were used to cascade factory …
> 🔨(edx) fix mysql seeding script for development

- CHANGELOG.md
- src/app/mork/api/models.py
- src/app/mork/celery/tasks/deletion.py
- src/app/mork/celery/tasks/emailing.py
- src/app/mork/edx/factories/student.py
- src/app/mork/tests/api/test_tasks.py
- src/app/mork/tests/celery/tasks/test_deletion_task.py
- src/app/mork/tests/celery/tasks/test_emailing_tasks.py
We need to avoid any unintended action through the API
Introduce safety measure for task execution:
- Add a dry\_run parameter to task creation API (defaults to True),
- Add a dry\_run parameter to tasks so they are still executed without
performing an action.
_Note:_ On a side note, fixing the MySQL dev seeding script that is still failing
> ✨(api) add dry-run mode to protect against unintended actions

- CHANGELOG.md
- src/app/logging-config.dev.yaml
- src/app/mork/api/__init__.py
- src/app/mork/api/routes/health.py
- src/app/mork/database.py
- src/app/mork/tests/api/test_health.py
The `__heartbeat__` endpoint occasionally returned HTTP 500 errors.
Session were not closed after requests, leading to the connection pool exhaustion.
Fixing it by making sure the session are properly managed.
> 🐛(api) fix session lifecycle on heartbeat endpoint

- CHANGELOG.md
- src/app/mork/celery/tasks/deletion.py
- src/app/mork/celery/tasks/edx.py
- src/app/mork/celery/utils.py
- src/app/mork/edx/mysql/crud.py
- src/app/mork/edx/mysql/factories/courseware.py
- src/app/mork/exceptions.py
- src/app/mork/tests/celery/tasks/test_deletion.py
- src/app/mork/tests/celery/tasks/test_edx.py
- src/app/mork/tests/celery/test_utils.py
- src/app/mork/tests/edx/mysql/test_crud.py
The deletion task of a user now includes a marking phase where user infos are stored in the Mork database before being deleted from edX.
Also refactored the edX deletion task into a new file, with a status check before deletion, and a status update after.
> ✨(celery) add marking of user before deletion

- CHANGELOG.md
- src/app/mork/api/v1/routers/tasks.py
- src/app/mork/celery/tasks/deletion.py
- src/app/mork/celery/tasks/emailing.py
- src/app/mork/schemas/tasks.py
- src/app/mork/tests/api/v1/routers/test_tasks.py
- src/app/mork/tests/celery/tasks/test_deletion.py
- src/app/mork/tests/celery/tasks/test_emailing.py
Currently, the tasks `delete_inactive_users` and `warn_inactive_users` process all inactive users in a single run. This "all-or-nothing" approach makes it difficult to validate results on smaller subsets
Add optional limit parameter to bulk deletion and warning tasks to allow for gradual processing of large user sets when needed.
> ✨(tasks) add limit parameter to bulk deletion and warning tasks

- CHANGELOG.md
- Dockerfile
When trying to send a warning email on preprod, email templates are not found.
Changes template copy path from '/app/src/app/mork/templates' to
'/app/mork/templates', ensuring that email templates are correctly loaded by
the Jinja2 template engine during task execution.
> 🔧(dockerfile) correct email template path

- CHANGELOG.md
- src/app/mork/api/v1/routers/tasks.py
- src/app/mork/api/v1/routers/users.py
- src/app/mork/tests/api/v1/routers/test_tasks.py
HTTP patch to users status endpoint has no impact on the user.
The update endpoint is not persisting changes to the database.
Adding session commit so the status update is persisted.
As we are only testing inside a same session, and we are avoiding any commit in the test suite, test remains the same.
On a side note, improving the task status endpoint path from `tasks/status/task_id` to `tasks/task_id/status`
> 🐛(api) ensure API status updates are committed to database

- CHANGELOG.md
- src/helm/mork/Chart.yaml
- src/helm/mork/templates/celery/deployment.yaml
Celery deployment selectors labels have been narrowed, but the Celery deployment
spec metadata is missing the celery component label.
Adding the missing component label and releasing a patch.
> 🔖(helm) bump release to 0.5.1

- CHANGELOG.md
- src/app/mork/celery/celery_app.py
- src/app/mork/celery/tasks/deletion.py
- src/app/mork/celery/tasks/edx.py
- src/app/mork/celery/tasks/emailing.py
- src/app/mork/edx/mongo/crud.py
- src/app/mork/edx/mysql/crud.py
- src/app/mork/exceptions.py
- src/app/mork/tests/celery/tasks/test_deletion.py
- src/app/mork/tests/celery/tasks/test_edx.py
- src/app/mork/tests/celery/tasks/test_emailing.py
- src/app/mork/tests/edx/mysql/test_crud.py
- src/helm/CHANGELOG.md
Some PII are sent to Sentry.
- Filtering out `email` and `username` fields using the SDK event scrubber.
- Removing PII from logs and exceptions
_On a side note, fixing a CHANGELOG mistake by relocating an entry from the Mork changelog to the Helm changelog._
> 🔇(sentry) filter emails and username from sentry events

- CHANGELOG.md
- src/app/mork/edx/mysql/crud.py
- src/app/mork/edx/mysql/factories/auth.py
- src/app/mork/edx/mysql/factories/wiki.py
- src/app/mork/edx/mysql/models/auth.py
- src/app/mork/edx/mysql/models/wiki.py
- src/app/mork/tests/edx/mysql/test_crud.py
The `wiki_article` and `wiki_articlerevision` tables references users through foreign key.
An error is raised when attempting to delete a user that owns a wiki article or a wiki article revision.
As we don't want entries from these tables to be removed, mapping them and adding them to the protected tables list.
> 🔒️(edx) map and add wiki tables to protected tables

- CHANGELOG.md
- src/app/mork/schemas/users.py
- src/app/mork/tests/api/v1/routers/test_users.py
Response from the user API is missing the `created_at` and `updated_at` datetimes.
Adding them.
> ✨(api) add created_at and updated_at to user response

- CHANGELOG.md
- src/app/mork/celery/celery_app.py
- src/app/mork/celery/probe.py
- src/helm/CHANGELOG.md
- src/helm/mork/templates/celery/deployment.yaml
Under heavy load (when deleting a lot of inactive users), the Celery liveness and readiness probes, based on the command `celery -A project inspect ping` uses a lot of CPU and is hanging before failing, resulting in a restart of the Celery worker pod.
To solve this, greatly inspired by https://github.com/celery/celery/issues/4079#issuecomment-1128954283 , adding:
- a custom liveness probe mechanism which periodically updates a local temporary file,
- a custom readiness probe mechanism which creates/deletes another local temporary file.
> 🩺(celery) add custom liveness and readiness probe

- src/helm/CHANGELOG.md
- src/helm/mork/Chart.yaml
- Add environment variables for Brevo configuration
- Change Celery liveness and readiness probes to file-based probes
- Upgrade appVersion to `0.6.0`
> 🔖(helm) bump release to 0.6.0

- CHANGELOG.md
- src/app/mork/celery/celery_app.py
Adding a before_send handler to filter out contact email from Brevo URLs in
breadcrumbs.
> 🔇(sentry) filter contact URLs in breadcrumbs

- src/helm/CHANGELOG.md
- src/helm/mork/Chart.yaml
- src/helm/mork/values.yaml
- Refactor API and Celery deployments to have specific deployment values
- Set Brevo API key from a secret instead of helm value
- Upgrade appVersion to `0.7.0`
> 🔖(helm) bump release to 0.7.0

- CHANGELOG.md
- docker-compose.yml
- src/app/mork/conf.py
When querying the PostgreSQL database with an email containing a non-ASCII character, a UnicodeEncodeError is raised. It seems the SQLAlchemy connection to the postgres db force encoding the string into ASCII.
To avoid this error, set the client encoding to utf8 in the connection URI.
Fixes #98
> 🐛(project) fix ascii encoding issue

- CHANGELOG.md
- src/app/mork/schemas/tasks.py
- src/app/mork/schemas/users.py
- src/app/mork/tests/api/v1/routers/test_tasks.py
- src/app/mork/tests/api/v1/routers/test_users.py
A validation error UserDeleteError is raised when trying to delete a user with
an incorrect email address, e.g. finishing with a '.'
Mork should not validate emails coming from edx, and should delete the user
anyway.
Removing pydantic `EmailStr` validation on `UserRead` model and `DeleteUser`
task class.
Fixes #103
> 🦺(project) remove email validation for emails coming from edx

- CHANGELOG.md
- src/app/mork/edx/mysql/factories/auth.py
- src/app/mork/edx/mysql/models/auth.py
- src/app/mork/edx/mysql/models/student.py
- src/app/mork/tests/edx/mysql/test_crud.py
- Deleting a user from edx MySQL that has an entry in the `auth_user_groups` table returns an `IntegrityError`.
- Deleting a user from edx MySQL that has is an enroller in the `student_manualenrollmentaudit` table (field `enrolled_by_id`) returns an `IntegrityError`.
- The `auth_user_groups` relation was incorrectly set to a one-to-one relationship instead of a many-to-one relationship. Fixing it. Fixes #97
- The relation for field `enrolled_by_id` was missing. Adding the relation, and since we don't want to delete entries from this table, and as the `enrolled_by_id` is nullable in the database, we do not specify a cascade behavior. As a result, the field is set to NULL by SQLAlchemy. Fixes #96
> 🐛(edx) fix auth_user_groups and student_manualenrollmentaudit relations

- CHANGELOG.md
- src/app/mork/celery/tasks/sarbacane.py
- src/app/mork/tests/celery/tasks/test_sarbacane.py
We were expecting a 404 Not Found when trying to delete a contact that is not
present in a list, but Sarbacane returns a 500 Internal Server Error.
> 🐛(sarbacane) fix incorrect status code check when deleting user contact
